# Generated by Django 5.2.8 on 2025-11-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0002_remove_pokemon_photo_pokemon_image_and_more'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='trainers.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'pokemon')},
            },
        ),
    ]
